"""add birthday column

Revision ID: 1e9abf7f89b9
Revises: 7f00526f157f
Create Date: 2026-05-02 14:35:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e9abf7f89b9'
down_revision: Union[str, None] = '7f00526f157f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    
    # Check if column exists in player_accounts
    check_account = conn.execute(sa.text(
        "SELECT 1 FROM information_schema.columns WHERE table_name='player_accounts' AND column_name='birthday'"
    )).fetchone()
    
    if not check_account:
        op.add_column('player_accounts', sa.Column('birthday', sa.String(), nullable=True))

    # Check if column exists in player_details
    check_detail = conn.execute(sa.text(
        "SELECT 1 FROM information_schema.columns WHERE table_name='player_details' AND column_name='birthday'"
    )).fetchone()
    
    if not check_detail:
        op.add_column('player_details', sa.Column('birthday', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    
    check_account = conn.execute(sa.text(
        "SELECT 1 FROM information_schema.columns WHERE table_name='player_accounts' AND column_name='birthday'"
    )).fetchone()
    if check_account:
        op.drop_column('player_accounts', 'birthday')
        
    check_detail = conn.execute(sa.text(
        "SELECT 1 FROM information_schema.columns WHERE table_name='player_details' AND column_name='birthday'"
    )).fetchone()
    if check_detail:
        op.drop_column('player_details', 'birthday')
    # ### end Alembic commands ###
