"""add_player_detail_columns

Revision ID: 4d5ab08543f0
Revises: a19785bd241b
Create Date: 2026-01-06 20:54:00.583070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d5ab08543f0'
down_revision: Union[str, None] = 'a19785bd241b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('health', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('xp_level', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('position_x', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('position_y', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('position_z', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_details', schema=None) as batch_op:
        batch_op.drop_column('position_z')
        batch_op.drop_column('position_y')
        batch_op.drop_column('position_x')
        batch_op.drop_column('xp_level')
        batch_op.drop_column('health')

    # ### end Alembic commands ###
