"""add_ip_to_bitacora

Revision ID: 957349673227
Revises: 0008
Create Date: 2026-01-04 18:49:08.931178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '957349673227'
down_revision: Union[str, None] = '0008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bitacora', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', sa.String(), nullable=True))

    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_servers_port'), ['port'])

    with op.batch_alter_table('versions', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_versions_name'), ['name'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('versions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_versions_name'), type_='unique')

    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_servers_port'), type_='unique')

    with op.batch_alter_table('bitacora', schema=None) as batch_op:
        batch_op.drop_column('ip_address')

    # ### end Alembic commands ###
