"""add_ip_to_bitacora

Revision ID: 957349673227
Revises: 0008
Create Date: 2026-01-04 18:49:08.931178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '957349673227'
down_revision: Union[str, None] = '0008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    
    # Check for ip_address in bitacora
    check_col = conn.execute(sa.text("SELECT 1 FROM information_schema.columns WHERE table_name='bitacora' AND column_name='ip_address'")).fetchone()
    if not check_col:
        with op.batch_alter_table('bitacora', schema=None) as batch_op:
            batch_op.add_column(sa.Column('ip_address', sa.String(), nullable=True))

    # Check for uq_servers_port in servers
    check_const = conn.execute(sa.text("SELECT 1 FROM information_schema.table_constraints WHERE table_name='servers' AND constraint_name='uq_servers_port'")).fetchone()
    if not check_const:
        with op.batch_alter_table('servers', schema=None) as batch_op:
            batch_op.create_unique_constraint(batch_op.f('uq_servers_port'), ['port'])

    # Check for uq_versions_name in versions
    check_v_const = conn.execute(sa.text("SELECT 1 FROM information_schema.table_constraints WHERE table_name='versions' AND constraint_name='uq_versions_name'")).fetchone()
    if not check_v_const:
        with op.batch_alter_table('versions', schema=None) as batch_op:
            batch_op.create_unique_constraint(batch_op.f('uq_versions_name'), ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('versions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_versions_name'), type_='unique')

    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_servers_port'), type_='unique')

    with op.batch_alter_table('bitacora', schema=None) as batch_op:
        batch_op.drop_column('ip_address')

    # ### end Alembic commands ###
