import typer
import sys
import os
import time
import subprocess

# Ensure parent is in sys.path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))

from database.migrate import run_migrations, rollback_migration, reset_database, show_current, show_history, create_database, PROJECT_ROOT
from database.seeder import run_all_seeders, run_specific_seeder
from rich.console import Console
from rich.prompt import Prompt
from rich.panel import Panel
from rich.progress import Progress, SpinnerColumn, TextColumn
from rich import print as rprint
from rich import box

app = typer.Typer(help="Ultimate Database Manager (PostgreSQL/SQLite)")
console = Console()

@app.callback(invoke_without_command=True)
def main(ctx: typer.Context):
    if ctx.invoked_subcommand is None:
        while True:
            console.clear()
            console.print(Panel.fit("[bold cyan]🗄️ DATABASE COMMAND CENTER[/bold cyan]", border_style="magenta", box=box.DOUBLE))
            
            console.print("[bold yellow]MIGRATIONS & SCHEMA[/bold yellow]")
            console.print(" [1] [green]Update Database[/green] (Auto-detect changes & Apply)")
            console.print(" [2] [blue]Run Migrations[/blue] (Apply pending files)")
            console.print(" [3] [red]Rollback[/red] (Undo last change)")
            
            console.print("\n[bold yellow]INITIALIZATION[/bold yellow]")
            console.print(" [4] [cyan]Initialize DB[/cyan] (First setup + Admin User)")
            console.print(" [5] [bold red]WIPE & RESET[/bold red] (Delete everything & Re-create)")
            
            console.print(" [7] Manage PG Roles (Users/Permissions)")
            
            console.print("\n[bold yellow]BACKUPS & RECOVERY[/bold yellow]")
            console.print(" [8] [green]Create Backup[/green] (Instant snapshot)")
            console.print(" [9] [yellow]Restore from Backup[/yellow] (Select a file)")
            
            console.print("\n [0] Return to Main Menu")
            
            choice = Prompt.ask("\n❯ Select an option", choices=["1", "2", "3", "4", "5", "6", "7", "8", "9", "0"], default="1")
            
            try:
                if choice == "1":
                    auto_update_cmd()
                elif choice == "2":
                    migrate_cmd()
                elif choice == "3":
                    rollback_cmd()
                elif choice == "4":
                    init_db_cmd()
                elif choice == "5":
                    reset_cmd()
                elif choice == "6":
                    seed_cmd(name="all")
                elif choice == "7":
                    roles_cmd()
                elif choice == "8":
                    create_backup_cmd()
                elif choice == "9":
                    restore_backup_cmd()
                elif choice == "0":
                    break
            except Exception as e:
                console.print(f"[bold red]Critical Error: {e}[/bold red]")
                
            Prompt.ask("\n[dim]Press Enter to continue...[/dim]")

@app.command("update")
def auto_update_cmd(message: str = typer.Option(None, "--message", "-m", help="Migration message")):
    """Auto-detect model changes, generate migration, and apply it."""
    console.print(Panel("[bold green]AUTODETECTING DATABASE CHANGES[/bold green]"))
    
    if not message:
        message = Prompt.ask("Enter a brief description of the changes", default=f"auto_migration_{int(time.time())}")

    with Progress(SpinnerColumn(), TextColumn("[cyan]Analyzing models & generating migration..."), console=console) as progress:
        task = progress.add_task("gen", total=None)
        
        # 1. Generate autogenerated migration
        res = subprocess.run(
            [sys.executable, "-m", "alembic", "revision", "--autogenerate", "-m", message],
            cwd=PROJECT_ROOT, capture_output=True, text=True
        )
        
        if res.returncode != 0:
            progress.stop()
            console.print(f"[bold red]Failed to generate migration:[/bold red]\n{res.stderr}")
            return False

        # 2. Apply migration
        progress.update(task, description="[green]Applying changes to database...")
        success = run_migrations()
        time.sleep(1)
        
    if success:
        console.print(f"[bold green]✓ Database schema updated successfully with revision: '{message}'[/bold green]")
    else:
        console.print("[bold red]✗ Failed to apply migration to database.[/bold red]")

@app.command("migrate")
def migrate_cmd():
    """Apply all pending migrations"""
    console.print("[cyan]Applying pending migrations...[/cyan]")
    if run_migrations():
        console.print("[bold green]✓ Migrations applied successfully.[/bold green]")
    else:
        console.print("[bold red]✗ Migration execution failed.[/bold red]")

@app.command("rollback")
def rollback_cmd():
    """Rollback the last migration"""
    if rollback_migration():
        console.print("[bold green]✓ Rollback completed.[/bold green]")
    else:
        console.print("[bold red]✗ Rollback failed.[/bold red]")

@app.command("init-db")
def init_db_cmd():
    """Initialize database and create an admin user"""
    console.print(Panel("[bold yellow]PostgreSQL & App Database Initialization[/bold yellow]"))
    
    import os
    import importlib
    
    # Check if we are using PostgreSQL
    engine_type = os.getenv("DB_ENGINE", "postgresql").lower()
    
    if engine_type != "sqlite":
        current_user = os.getenv("DB_USER", "postgres")
        console.print(f"Current database user in .env: [cyan]{current_user}[/cyan]")
        
        setup_pg = Prompt.ask("Setup PostgreSQL credentials now?", choices=["y", "n"], default="y")
        if setup_pg == "y":
            new_user = Prompt.ask("PG Username", default="mine_admin")
            while True:
                p1 = Prompt.ask(f"Password for '{new_user}'", password=True)
                p2 = Prompt.ask("Repeat password", password=True)
                if p1 == p2:
                    selected_password = p1
                    break
                console.print("[red]Passwords don't match![/red]")
            
            db_host = os.getenv("DB_HOST", "127.0.0.1")
            db_port = os.getenv("DB_PORT", "5432")
            db_name = os.getenv("DB_NAME", "mine_db")
            
            is_linux = sys.platform != 'win32'
            auth_method = "1"
            if is_linux:
                console.print("[1] Password (PG Superuser) | [2] Sudo (Linux Root)")
                auth_method = Prompt.ask("Method", choices=["1", "2"], default="1")

            try:
                from dev.utils.database import bootstrap_postgres_db, bootstrap_postgres_db_sudo
                if auth_method == "2":
                    u, p = bootstrap_postgres_db_sudo(db_name, new_user, selected_password, db_host, db_port)
                else:
                    s_user = Prompt.ask("Superuser (e.g. postgres)", default="postgres")
                    s_pass = Prompt.ask(f"Password for {s_user}", password=True)
                    u, p = bootstrap_postgres_db(db_host, db_port, db_name, s_user, s_pass, new_user, selected_password)
                
                os.environ["DB_USER"] = u
                os.environ["DB_PASSWORD"] = p
                import database.connection
                importlib.reload(database.connection)
                console.print("[bold green]✓ PostgreSQL Credentials Configured.[/bold green]")
            except Exception as e:
                console.print(f"[bold red]PG Setup Error: {e}[/bold red]")
                if Prompt.ask("Abort initialization?", choices=["y", "n"], default="y") == "y": return

    # SQL Alchemy Table Creation
    with Progress(SpinnerColumn(), TextColumn("[cyan]Building tables..."), console=console) as progress:
        progress.add_task("init", total=None)
        import database.migrate
        importlib.reload(database.migrate)
        from database.migrate import create_database as dynamic_create_database
        success = dynamic_create_database()
        
    if success:
        console.print("[bold green]✓ Tables created & Alembic stamped.[/bold green]")
        _create_app_admin()
    else:
        console.print("[bold red]✗ Initialization failed.[/bold red]")

def _create_app_admin():
    console.print("\n[bold cyan]Creating App Administrator Account[/bold cyan]")
    username = Prompt.ask("Admin Username", default="admin")
    password = Prompt.ask("Admin Password", password=True)
    
    from database.connection import SessionLocal
    from database.models.user import User
    from app.services.auth_service import get_password_hash
    
    db = SessionLocal()
    try:
        if db.query(User).filter(User.username == username).first():
            console.print(f"[yellow]User {username} already exists.[/yellow]")
        else:
            db.add(User(username=username, hashed_password=get_password_hash(password), is_admin=True))
            db.commit()
            console.print("[bold green]✓ Admin account created.[/bold green]")
    except Exception as e:
        console.print(f"[red]Error: {e}[/red]")
        db.rollback()
    finally:
        db.close()

@app.command("reset")
def reset_cmd():
    """Reset database (Wipe all)"""
    console.print(Panel("[bold red]DANGER: THIS WILL WIPE ALL DATABASE DATA[/bold red]", border_style="red"))
    confirm = Prompt.ask("Type 'RESET' to confirm destruction", default="")
    if confirm == "RESET":
        with Progress(SpinnerColumn(), TextColumn("[red]Wiping database..."), console=console) as progress:
            progress.add_task("reset", total=None)
            success = reset_database()
            time.sleep(1)
        if success:
            console.print("[bold green]✓ Database wiped & reset to empty state.[/bold green]")
        else:
            console.print("[bold red]✗ Reset failed.[/bold red]")
    else:
        console.print("[yellow]Reset aborted.[/yellow]")

@app.command("backup")
def create_backup_cmd():
    """Create a new database backup"""
    from app.services.backup_service import BackupService
    service = BackupService()
    
    console.print("[cyan]Generating full system snapshot (DB + Servers)...[/cyan]")
    try:
        filename = service.create_full_backup()
        console.print(f"[bold green]✓ Full backup created: {filename}[/bold green]")
    except Exception as e:
        console.print(f"[bold red]✗ Backup failed: {e}[/bold red]")

@app.command("restore")
def restore_backup_cmd():
    """Restore database from a backup file"""
    from app.services.backup_service import BackupService
    service = BackupService()
    
    backups = service.list_backups()
    if not backups:
        console.print("[yellow]No backups found in 'backups/' directory.[/yellow]")
        return
    
    console.print("\n[bold cyan]Select a backup to restore:[/bold cyan]")
    table = Table(show_header=True, header_style="bold yellow", box=box.SIMPLE)
    table.add_column("No.", style="dim")
    table.add_column("Filename")
    table.add_column("Size (MB)")
    table.add_column("Date")
    
    for i, b in enumerate(backups):
        size_mb = round(b['size'] / (1024 * 1024), 2)
        table.add_row(str(i+1), b['filename'], str(size_mb), b['created_at'])
    
    console.print(table)
    idx = Prompt.ask("\n❯ Enter number to restore (or 0 to cancel)", default="0")
    
    if idx == "0": return
    
    try:
        selected = backups[int(idx)-1]
        console.print(Panel(f"[bold red]DANGER: Restoring will overwrite current database with data from:[/bold red]\n{selected['filename']}", border_style="red"))
        confirm = Prompt.ask("Type 'RESTORE' to confirm", default="")
        
        if confirm == "RESTORE":
            if service.restore_full_backup(selected['filename']):
                console.print("[bold green]✓ System restored successfully![/bold green]")
            else:
                console.print("[bold red]✗ Restore failed.[/bold red]")
        else:
            console.print("[yellow]Restore cancelled.[/yellow]")
    except (ValueError, IndexError):
        console.print("[red]Invalid selection.[/red]")
    except Exception as e:
        console.print(f"[bold red]✗ Error during restore: {e}[/bold red]")
    # ... (Keeping your existing roles logic but improved error handling)
    console.print(Panel("[bold yellow]PostgreSQL Role Management[/bold yellow]"))
    import os
    db_host = os.getenv("DB_HOST", "127.0.0.1")
    db_port = os.getenv("DB_PORT", "5432")
    super_user = Prompt.ask("Superuser (postgres)", default="postgres")
    super_pass = Prompt.ask(f"Password for {super_user}", password=True)
    
    try:
        import psycopg2
        from psycopg2 import sql
        from psycopg2.extensions import ISOLATION_LEVEL_AUTOCOMMIT
        conn = psycopg2.connect(dbname="postgres", user=super_user, password=super_pass, host=db_host, port=db_port)
        conn.set_isolation_level(ISOLATION_LEVEL_AUTOCOMMIT)
        cur = conn.cursor()
        while True:
            cur.execute("SELECT rolname FROM pg_roles WHERE rolcanlogin = true ORDER BY rolname;")
            roles = [r[0] for r in cur.fetchall()]
            console.print(f"\n[bold cyan]Roles:[/bold cyan] {', '.join(roles)}")
            console.print("[1] Create [2] Passwd [3] Drop [0] Back")
            sub = Prompt.ask("Action", choices=["1", "2", "3", "0"], default="0")
            if sub == "1":
                r = Prompt.ask("Name"); p = Prompt.ask("Pass", password=True)
                cur.execute(sql.SQL("CREATE USER {} WITH PASSWORD {}").format(sql.Identifier(r), sql.Literal(p)))
            elif sub == "2":
                r = Prompt.ask("Role", choices=roles); p = Prompt.ask("New Pass", password=True)
                cur.execute(sql.SQL("ALTER USER {} WITH PASSWORD {}").format(sql.Identifier(r), sql.Literal(p)))
            elif sub == "3":
                r = Prompt.ask("Role", choices=roles)
                cur.execute(sql.SQL("DROP USER {}").format(sql.Identifier(r)))
            elif sub == "0": break
        cur.close(); conn.close()
    except Exception as e:
        console.print(f"[bold red]PG Error: {e}[/bold red]")

if __name__ == "__main__":
    app()
