import typer
import sys
import os
import time
import subprocess
from typing import Optional

# Ensure parent is in sys.path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))

from database.migrate import run_migrations, rollback_migration, reset_database, show_current, show_history, create_database, PROJECT_ROOT
from database.seeder import run_all_seeders, run_specific_seeder
from rich.console import Console
from rich.prompt import Prompt
from rich.panel import Panel
from rich.progress import Progress, SpinnerColumn, TextColumn
from rich.table import Table
from rich import print as rprint
from rich import box

app = typer.Typer(help="Ultimate Database Manager (PostgreSQL/SQLite)")
console = Console()

@app.callback(invoke_without_command=True)
def main(ctx: typer.Context):
    if ctx.invoked_subcommand is None:
        while True:
            console.clear()
            console.print(Panel.fit("[bold cyan]🗄️ DATABASE COMMAND CENTER[/bold cyan]", border_style="magenta", box=box.DOUBLE))
            
            console.print("[bold yellow]MIGRATIONS & SCHEMA[/bold yellow]")
            console.print(" [1] [green]Update Database[/green] (Auto-detect changes & Apply)")
            console.print(" [2] [blue]Run Migrations[/blue] (Apply pending files)")
            console.print(" [3] [red]Rollback[/red] (Undo last change)")
            
            console.print("\n[bold yellow]INITIALIZATION[/bold yellow]")
            console.print(" [4] [cyan]Initialize DB[/cyan] (First setup + Admin User)")
            console.print(" [5] [bold red]WIPE & RESET[/bold red] (Delete everything & Re-create)")
            
            console.print("\n[bold yellow]DATA & ACCESS[/bold yellow]")
            console.print(" [6] Populate Seeders (Dummy data)")
            console.print(" [7] Manage PG Roles (Users/Permissions)")
            
            console.print("\n[bold yellow]BACKUPS & RECOVERY[/bold yellow]")
            console.print(" [8] [green]Create Backup[/green] (Instant snapshot)")
            console.print(" [9] [yellow]Restore from Backup[/yellow] (Select a file)")
            
            console.print("\n[bold red]TOOLS[/bold red]")
            console.print(" [10] [bold white]Fix Missing Columns[/bold white] (Manual SQL injection)")
            
            console.print("\n [0] Return to Main Menu")
            
            choice = Prompt.ask("\n❯ Select an option", choices=["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "0"], default="1")
            
            try:
                if choice == "1":
                    auto_update_cmd(None) # Pass None to trigger prompt
                elif choice == "2":
                    migrate_cmd()
                elif choice == "3":
                    rollback_cmd()
                elif choice == "4":
                    init_db_cmd()
                elif choice == "5":
                    reset_cmd()
                elif choice == "6":
                    seed_cmd("all")
                elif choice == "7":
                    roles_cmd()
                elif choice == "8":
                    create_backup_cmd()
                elif choice == "10":
                    fix_schema_cmd()
                elif choice == "0":
                    break
            except Exception as e:
                console.print(f"[bold red]Critical Error: {e}[/bold red]")
                
            Prompt.ask("\n[dim]Press Enter to continue...[/dim]")

@app.command("update")
def auto_update_cmd(message: Optional[str] = typer.Option(None, "--message", "-m", help="Migration message")):
    """Auto-detect model changes, generate migration, and apply it."""
    console.print(Panel("[bold green]AUTODETECTING DATABASE CHANGES[/bold green]"))
    
    # Handle the case where message is passed as a Typer Option object instead of string
    if not isinstance(message, str):
        message = None

    if not message:
        message = Prompt.ask("Enter a brief description of the changes", default=f"auto_migration_{int(time.time())}")

    with Progress(SpinnerColumn(), TextColumn("[cyan]Analyzing models & generating migration..."), console=console) as progress:
        task = progress.add_task("gen", total=None)
        
        # 1. Try to generate autogenerated migration
        def try_generate():
            return subprocess.run(
                [sys.executable, "-m", "alembic", "revision", "--autogenerate", "-m", message],
                cwd=PROJECT_ROOT, capture_output=True, text=True
            )

        res = try_generate()
        
        if res.returncode != 0:
            err_output = (res.stderr or "") + (res.stdout or "")
            
            # AUTOMATIC CONFLICT RESOLUTION
            if "Target database is not up to date" in err_output or "Multiple heads" in err_output:
                progress.update(task, description="[yellow]Conflict detected. Cleaning and syncing DB...")
                
                # 1. Manual SQL clean if multiple heads in DB
                if "Multiple heads" in err_output:
                    from sqlalchemy import text
                    from database.connection import get_engine
                    try:
                        with get_engine().connect() as conn:
                            conn.execute(text("DELETE FROM alembic_version"))
                            conn.commit()
                    except: pass

                # 2. Sync DB to current heads
                subprocess.run([sys.executable, "-m", "alembic", "stamp", "heads"], cwd=PROJECT_ROOT)
                
                # 3. If it's still failing with "Multiple heads", it means the FILES have multiple heads.
                # Let's try to merge them automatically.
                if "Multiple heads are present" in err_output or "specify a single target revision" in err_output:
                    progress.update(task, description="[yellow]Multiple heads in files. Merging migrations...")
                    subprocess.run([sys.executable, "-m", "alembic", "merge", "heads", "-m", "merge_heads_auto"], cwd=PROJECT_ROOT)

                # Second attempt
                progress.update(task, description="[cyan]Retrying migration generation...")
                res = try_generate()

            if res.returncode != 0:
                progress.stop()
                console.print(f"[bold red]Failed to generate migration:[/bold red]\n{res.stderr or res.stdout}")
                return False

        # 2. Apply migration
        progress.update(task, description="[green]Applying changes to database...")
        success = run_migrations()
        time.sleep(1)
        
    if success:
        console.print(f"[bold green]✓ Database schema updated successfully with revision: '{message}'[/bold green]")
    else:
        console.print("[bold red]✗ Failed to apply migration to database.[/bold red]")

@app.command("migrate")
def migrate_cmd():
    """Apply all pending migrations"""
    console.print("[cyan]Applying pending migrations...[/cyan]")
    if run_migrations():
        console.print("[bold green]✓ Migrations applied successfully.[/bold green]")
    else:
        console.print("[bold red]✗ Migration execution failed.[/bold red]")

@app.command("rollback")
def rollback_cmd():
    """Rollback the last migration"""
    if rollback_migration():
        console.print("[bold green]✓ Rollback completed.[/bold green]")
    else:
        console.print("[bold red]✗ Rollback failed.[/bold red]")

@app.command("init-db")
def init_db_cmd():
    """Initialize database and create an admin user"""
    console.print(Panel("[bold yellow]PostgreSQL & App Database Initialization[/bold yellow]"))
    
    import importlib
    
    # Check if we are using PostgreSQL
    engine_type = os.getenv("DB_ENGINE", "postgresql").lower()
    
    if engine_type != "sqlite":
        current_user = os.getenv("DB_USER", "postgres")
        console.print(f"Current database user in .env: [cyan]{current_user}[/cyan]")
        
        setup_pg = Prompt.ask("Setup PostgreSQL credentials now?", choices=["y", "n"], default="y")
        if setup_pg == "y":
            new_user = Prompt.ask("PG Username", default="mine_admin")
            while True:
                p1 = Prompt.ask(f"Password for '{new_user}'", password=True)
                p2 = Prompt.ask("Repeat password", password=True)
                if p1 == p2:
                    selected_password = p1
                    break
                console.print("[red]Passwords don't match![/red]")
            
            db_host = os.getenv("DB_HOST", "127.0.0.1")
            db_port = os.getenv("DB_PORT", "5432")
            db_name = os.getenv("DB_NAME", "mine_db")
            
            is_linux = sys.platform != 'win32'
            auth_method = "1"
            if is_linux:
                console.print("[1] Password (PG Superuser) | [2] Sudo (Linux Root)")
                auth_method = Prompt.ask("Method", choices=["1", "2"], default="1")

            try:
                from dev.utils.database import bootstrap_postgres_db, bootstrap_postgres_db_sudo
                if auth_method == "2":
                    u, p = bootstrap_postgres_db_sudo(db_name, new_user, selected_password, db_host, db_port)
                else:
                    s_user = Prompt.ask("Superuser (e.g. postgres)", default="postgres")
                    s_pass = Prompt.ask(f"Password for {s_user}", password=True)
                    u, p = bootstrap_postgres_db(db_host, db_port, db_name, s_user, s_pass, new_user, selected_password)
                
                os.environ["DB_USER"] = u
                os.environ["DB_PASSWORD"] = p
                import database.connection
                importlib.reload(database.connection)
                console.print("[bold green]✓ PostgreSQL Credentials Configured.[/bold green]")
            except Exception as e:
                console.print(f"[bold red]PG Setup Error: {e}[/bold red]")
                if Prompt.ask("Abort initialization?", choices=["y", "n"], default="y") == "y": return

    # SQL Alchemy Table Creation
    with Progress(SpinnerColumn(), TextColumn("[cyan]Building tables..."), console=console) as progress:
        progress.add_task("init", total=None)
        import database.migrate
        importlib.reload(database.migrate)
        from database.migrate import create_database as dynamic_create_database
        success = dynamic_create_database()
        
    if success:
        console.print("[bold green]✓ Tables created & Alembic stamped.[/bold green]")
        _create_app_admin()
    else:
        console.print("[bold red]✗ Initialization failed.[/bold red]")

def _create_app_admin():
    console.print("\n[bold cyan]Creating App Administrator Account[/bold cyan]")
    username = Prompt.ask("Admin Username", default="admin")
    password = Prompt.ask("Admin Password", password=True)
    
    from database.connection import SessionLocal
    from database.models.user import User
    from app.services.auth_service import get_password_hash
    
    db = SessionLocal()
    try:
        if db.query(User).filter(User.username == username).first():
            console.print(f"[yellow]User {username} already exists.[/yellow]")
        else:
            db.add(User(username=username, hashed_password=get_password_hash(password), is_admin=True))
            db.commit()
            console.print("[bold green]✓ Admin account created.[/bold green]")
    except Exception as e:
        console.print(f"[red]Error: {e}[/red]")
        db.rollback()
    finally:
        db.close()

@app.command("reset")
def reset_cmd():
    """Reset database (Wipe all)"""
    console.print(Panel("[bold red]DANGER: THIS WILL WIPE ALL DATABASE DATA[/bold red]", border_style="red"))
    confirm = Prompt.ask("Type 'RESET' to confirm destruction", default="")
    if confirm == "RESET":
        with Progress(SpinnerColumn(), TextColumn("[red]Wiping database..."), console=console) as progress:
            progress.add_task("reset", total=None)
            success = reset_database()
            time.sleep(1)
        if success:
            console.print("[bold green]✓ Database wiped & reset to empty state.[/bold green]")
        else:
            console.print("[bold red]✗ Reset failed.[/bold red]")
    else:
        console.print("[yellow]Reset aborted.[/yellow]")

@app.command("seed")
def seed_cmd(name: str = "all"):
    """Populate database with seed data"""
    if name == "all":
        run_all_seeders()
    else:
        run_specific_seeder(name)
    console.print("[bold green]✓ Seeding completed.[/bold green]")

@app.command("backup")
def create_backup_cmd():
    """Create a new full system backup"""
    from app.services.backup_service import BackupService
    service = BackupService()
    
    console.print("[cyan]Generating full system snapshot (DB + Servers + Loaders)...[/cyan]")
    try:
        filename = service.create_full_backup()
        console.print(f"[bold green]✓ Full backup created: {filename}[/bold green]")
    except Exception as e:
        console.print(f"[bold red]✗ Backup failed: {e}[/bold red]")

@app.command("restore")
def restore_backup_cmd():
    """Restore system from a backup file"""
    from app.services.backup_service import BackupService
    service = BackupService()
    
    backups = service.list_backups()
    if not backups:
        console.print("[yellow]No backups found in 'backups/' directory.[/yellow]")
        return
    
    console.print("\n[bold cyan]Select a backup to restore:[/bold cyan]")
    table = Table(show_header=True, header_style="bold yellow", box=box.SIMPLE)
    table.add_column("No.", style="dim")
    table.add_column("Filename")
    table.add_column("Size (MB)")
    table.add_column("Date")
    
    for i, b in enumerate(backups):
        size_mb = round(b['size'] / (1024 * 1024), 2)
        table.add_row(str(i+1), b['filename'], str(size_mb), b['created_at'])
    
    console.print(table)
    idx = Prompt.ask("\n❯ Enter number to restore (or 0 to cancel)", default="0")
    
    if idx == "0": return
    
    try:
        selected = backups[int(idx)-1]
        console.print(Panel(f"[bold red]DANGER: Restoring will overwrite EVERYTHING (DB, Worlds, Mods) with data from:[/bold red]\n{selected['filename']}", border_style="red"))
        confirm = Prompt.ask("Type 'RESTORE' to confirm", default="")
        
        if confirm == "RESTORE":
            if service.restore_full_backup(selected['filename']):
                console.print("[bold green]✓ System restored successfully![/bold green]")
            else:
                console.print("[bold red]✗ Restore failed.[/bold red]")
        else:
            console.print("[yellow]Restore cancelled.[/yellow]")
    except (ValueError, IndexError):
        console.print("[red]Invalid selection.[/red]")
    except Exception as e:
        console.print(f"[bold red]✗ Error during restore: {e}[/bold red]")

@app.command("roles")
def roles_cmd():
    """Manage PostgreSQL database roles (users)"""
    console.print(Panel("[bold yellow]PostgreSQL Role Management[/bold yellow]"))
    db_host = os.getenv("DB_HOST", "127.0.0.1")
    db_port = os.getenv("DB_PORT", "5432")
    super_user = Prompt.ask("Superuser (postgres)", default="postgres")
    super_pass = Prompt.ask(f"Password for {super_user}", password=True)
    
    try:
        import psycopg2
        from psycopg2 import sql
        from psycopg2.extensions import ISOLATION_LEVEL_AUTOCOMMIT
        conn = psycopg2.connect(dbname="postgres", user=super_user, password=super_pass, host=db_host, port=db_port)
        conn.set_isolation_level(ISOLATION_LEVEL_AUTOCOMMIT)
        cur = conn.cursor()
        while True:
            cur.execute("SELECT rolname FROM pg_roles WHERE rolcanlogin = true ORDER BY rolname;")
            roles = [r[0] for r in cur.fetchall()]
            console.print(f"\n[bold cyan]Roles:[/bold cyan] {', '.join(roles)}")
            console.print("[1] Create User [2] Change Password [3] Drop User [0] Back")
            sub = Prompt.ask("Action", choices=["1", "2", "3", "0"], default="0")
            if sub == "1":
                r = Prompt.ask("Username"); p = Prompt.ask("Password", password=True)
                cur.execute(sql.SQL("CREATE USER {} WITH PASSWORD {}").format(sql.Identifier(r), sql.Literal(p)))
                console.print(f"[green]User {r} created.[/green]")
            elif sub == "2":
                r = Prompt.ask("Role", choices=roles); p = Prompt.ask("New Password", password=True)
                cur.execute(sql.SQL("ALTER USER {} WITH PASSWORD {}").format(sql.Identifier(r), sql.Literal(p)))
                console.print(f"[green]Password changed for {r}.[/green]")
            elif sub == "3":
                r = Prompt.ask("Role", choices=roles)
                cur.execute(sql.SQL("DROP USER {}").format(sql.Identifier(r)))
                console.print(f"[green]User {r} dropped.[/green]")
            elif sub == "0": break
        cur.close(); conn.close()
    except Exception as e:
        console.print(f"[bold red]PG Error: {e}[/bold red]")

@app.command("fix-schema")
def fix_schema_cmd():
    """Manually add missing statistics columns to the database (Raw SQL)"""
    from database.connection import get_engine
    from sqlalchemy import text
    
    console.print(Panel("[bold yellow]MANUAL SCHEMA REPAIR[/bold yellow]"))
    console.print("[cyan]Applying raw SQL to fix missing statistics columns...[/cyan]")
    
    queries = [
        "ALTER TABLE player_accounts ADD COLUMN IF NOT EXISTS total_player_kills INTEGER DEFAULT 0;",
        "ALTER TABLE player_accounts ADD COLUMN IF NOT EXISTS total_hostile_kills INTEGER DEFAULT 0;",
        "ALTER TABLE player_accounts ADD COLUMN IF NOT EXISTS total_genocide_score INTEGER DEFAULT 0;"
    ]
    
    engine = get_engine()
    try:
        with engine.connect() as conn:
            for query in queries:
                console.print(f"Running: [dim]{query}[/dim]")
                try:
                    conn.execute(text(query))
                    conn.commit()
                except Exception as ex:
                    if "already exists" in str(ex).lower() or "duplicate column" in str(ex).lower():
                        console.print(f"[yellow]Column already exists, skipping.[/yellow]")
                    else:
                        console.print(f"[red]Error on query: {ex}[/red]")
                        
        console.print("[bold green]✓ Database schema repaired successfully.[/bold green]")
    except Exception as e:
        console.print(f"[bold red]✗ Failed to repair schema: {e}[/bold red]")

if __name__ == "__main__":
    app()
